### ISSUE TITLE
Generate Kubernetes Go types for new k8s version

### ISSUE THREAD

**Issue by jvanz** [kubewarden/k8s-objects#19]
Is this branch ready to be pushed to upstream repository?

https://github.com/jvanz/k8s-objects/tree/release-1.31

**Comment by viccuad** [comment]
LGTM! I think it is fine :green_heart:  .

**Comment by flavio** [comment]
LGTM too, go ahead! 🚀

**Comment by jvanz** [comment]
Done https://github.com/kubewarden/k8s-objects/tree/release-1.31
