### ISSUE TITLE
Missing tag v1.31.0-kw1

### ISSUE THREAD

**Issue by rd-niklas-gergs** [kubewarden/k8s-objects#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Awesome project!

Question regarding issue #19 

The release `release-1.31` is there but the tag `v1.31.0-kw1` not. Is this intended?

### Expected Behavior

Tag `v1.31.0-kw1` is present.

### Steps To Reproduce

```bash
go get github.com/kubewarden/k8s-objects@v1.31.0-kw1
```

**Comment by flavio** [comment]
I've just pushed the tag. Thanks for the report!

**Comment by flavio** [comment]
JFYI: I've also pushed the 1.32 objects too
